"""Determinism helpers.

Every builder that consumes randomness imports ``seeded_context`` and uses it
as a context manager so the seed scope is explicit and auditable.

The canonical seed is ``20260416`` (YYYYMMDD of the implementation plan's
authoring date), also exposed via ``CANONICAL_SEED``. Pass a different seed
only when producing a variant corpus for ablation.
"""

from __future__ import annotations

import os
import random
import shutil
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import Final

from .exceptions import DeterminismError
from .io import iter_build_artifacts, sha256_file

CANONICAL_SEED: Final[int] = 20260416
"""The standard seed for all deterministic generators."""

OUT_OF_BAND_PREFIXES: Final[tuple[str, ...]] = (
    # Produced by the Swift test target running against the G8 corpus, not by
    # `make build`. Preserved here only as reference input for calibration.
    "calibration/",
    # Produced by `make calibrate-{temperature,sweep,finalize}`, gated on the
    # two dumps above. The sweep_raw file is the 0.4 two-stage inspection
    # artifact; the shipping preset_thresholds.json is written only by the
    # finalize step.
    "classifier/doctype_temperature.json",
    "classifier/preset_thresholds.json",
    "classifier/preset_thresholds_sweep_raw.json",
    # Produced by the agent / human negative-context review step. The
    # adjacent candidates file IS regenerated by `make build` and
    # participates in determinism.
    "gazetteers/negative_context.json",
    "gazetteers/negative_context.meta.json",
    # Produced by an authoring workflow (dl_patterns, dd_patterns candidates
    # files) — authored once per research cycle, changed under an approved
    # change plan, then consumed as input by the shipping-artifact builders.
    # Not regenerated by `make build`, so the determinism-check must preserve
    # these across rebuild. passport_patterns and dl_patterns moved their
    # candidates files to src/resecta_data/gazetteers/<module>/sources/;
    # relocating the remaining candidates files the same way is pending.
    "gazetteers/sources/",
    # Signed-manifest peer files produced by `make sign-manifest`
    # (not by `make build`). Ed25519 signing is deterministic for fixed
    # (key, message), but the rebuild-and-diff scope is just `make build`
    # so these files appear as "extra" on the original build. Exclude from
    # determinism + hash-lock checks; correctness of the signature itself
    # is enforced by tests/test_signed_manifest.py and the iOS verifier.
    "gazetteers/gazetteer_manifest.sig",
    "gazetteers/manifest_public_key.pem",
    # Search-eval substrate — committed/reference eval fixtures that
    # `make build` does NOT regenerate: the G8 per-fire feature dump is emitted
    # by the iOS G8 harness and committed; the negative corpus is the baseline
    # fixture. Like the calibration dumps above, they are reference
    # inputs the eval path reads, so they fail the determinism rebuild + the
    # hash-lock bijection unless excluded — classify them out-of-band (the
    # committed-not-rebuilt pattern). Reconciles a gap where these fixtures
    # ran schema-check-only, never full `gmake verify`.
    "corpus/g8_fire_features.json",
    "corpus/negative_corpus.json",
)
"""Build-relative paths produced by stages other than ``make build``.

Lives here (not in ``cli.py``) so every walker that needs the out-of-band
notion — the determinism/hash verifiers in the CLI and the bundle-size probe
in ``instrumentation/bundle_size.py`` — shares one definition. The probe
carrying no out-of-band awareness is how the signed-manifest products got
baked into locked bytes.
"""


def is_out_of_band(rel_path: str) -> bool:
    """Return True for paths produced by stages other than ``make build``.

    Covers calibration dumps, calibrated outputs, hand-review gates, and the
    signed-manifest products (see :data:`OUT_OF_BAND_PREFIXES`). These are
    excluded from determinism checks because the rebuild command doesn't
    regenerate them.
    """
    return any(rel_path == p or rel_path.startswith(p) for p in OUT_OF_BAND_PREFIXES)


@contextmanager
def seeded_context(seed: int) -> Iterator[random.Random]:
    """Yield a ``random.Random`` instance seeded with ``seed``.

    Prefer this over the module-level ``random`` functions because the
    module-level API shares global state, which is non-reentrant and leaks
    state across builders.

    Args:
        seed: Non-negative integer seed.

    Yields:
        A freshly seeded ``random.Random`` instance.

    Raises:
        DeterminismError: If ``seed`` is negative.
    """
    if seed < 0:
        raise DeterminismError(f"Seed must be non-negative, got {seed}")
    rng = random.Random(seed)  # noqa: S311 — not for security
    yield rng


def assert_hash_seed_pinned() -> None:
    """Ensure ``PYTHONHASHSEED`` is ``0``.

    Pytest config pins this, but CLIs invoked outside pytest must check
    explicitly. Hash randomization can leak into dict iteration order in
    subtle ways that break reproducibility.

    Raises:
        DeterminismError: If ``PYTHONHASHSEED`` is unset or non-zero.
    """
    value = os.environ.get("PYTHONHASHSEED")
    if value != "0":
        raise DeterminismError(
            f"PYTHONHASHSEED must be '0' for deterministic builds, got {value!r}. "
            "Set via `export PYTHONHASHSEED=0` before invoking."
        )


def snapshot_build_dir(build_dir: Path, dest: Path) -> dict[str, str]:
    """Copy every file in ``build_dir`` into ``dest`` and return their hashes.

    Used by the determinism verifier: it builds once, snapshots, builds again,
    then compares hashes. Any difference is a determinism defect.

    Args:
        build_dir: Source directory.
        dest: Destination directory. Created if missing; cleared if present.

    Returns:
        Dict mapping relative path (as POSIX string) to hex SHA-256.
    """
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)

    hashes: dict[str, str] = {}
    for src_path in iter_build_artifacts(build_dir):
        rel = src_path.relative_to(build_dir)
        dst_path = dest / rel
        dst_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src_path, dst_path)
        hashes[rel.as_posix()] = sha256_file(dst_path)
    return hashes


def diff_hash_maps(first: dict[str, str], second: dict[str, str]) -> list[str]:
    """Return human-readable descriptions of every difference between two hash maps.

    An empty return list means the builds are bit-identical.
    """
    differences: list[str] = []

    only_first = sorted(set(first) - set(second))
    only_second = sorted(set(second) - set(first))
    common = sorted(set(first) & set(second))

    differences.extend(f"Only in first build: {p}" for p in only_first)
    differences.extend(f"Only in second build: {p}" for p in only_second)
    differences.extend(
        f"Hash differs for {p}: {first[p][:12]}... vs {second[p][:12]}..."
        for p in common
        if first[p] != second[p]
    )

    return differences
